# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: null # Standardní správa session v souborech

    #esi: true
    #fragments: true


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
